package com.suzuki.bike.entity.enums;

public enum ServiceType {
    OIL_CHANGE,
    ENGINE_REPAIR,
    TIRE_REPLACEMENT,
    BRAKE_SERVICE,
    BATTERY_REPLACEMENT,
    CHAIN_ADJUSTMENT,
    CHAIN_REPLACEMENT,
    SUSPENSION_REPAIR,
    ELECTRICAL_REPAIR,
    GENERAL_INSPECTION,
    FULL_SERVICE,
    CLUTCH_REPAIR,
    GEAR_REPAIR,
    COOLING_SYSTEM_REPAIR,
    FUEL_SYSTEM_CLEANING,
    AIR_FILTER_REPLACEMENT,
    SPARK_PLUG_REPLACEMENT,
    WHEEL_ALIGNMENT,
    WASHING_DETAILING,
    OTHER
}
